apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secrets-store
auth:
  secretStore: strongbox
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      secretKeyRef:
        key: keyvaultName
        name: keyvaultName
    - name: azureTenantId
      secretKeyRef:
        key: tenant
        name: tenant
    - name: azureClientId
      secretKeyRef:
        key: appId
        name: appId
    - name: azureClientSecret
      secretKeyRef:
        key: password
        name: password
