---
rules:
  braces:
    forbid: true
    level: error
  brackets:
    forbid: true
    level: warning
  colons:
    level: error
  commas:
    level: error
  comments:
    level: error
  comments-indentation:
    level: error
  document-end:
    present: false
  document-start:
    level: warning
  empty-lines:
    max: 2
    level: warning
  empty-values: disable
  hyphens:
    level: error
  indentation:
    level: warning
  key-duplicates:
    level: error
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file:
    level: warning
  new-lines:
    type: unix
    level: warning
  octal-values: disable
  trailing-spaces:
    level: warning
  truthy:
    level: warning
