receivers:
  zipkin: 
extensions:
  health_check: 
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
exporters:
  logging:
    loglevel: debug
  azuremonitor:
    instrumentation_key: 65c5de3e-cde3-4306-9886-97013c10d69a
    maxbatchinterval: 5s
    maxbatchsize: 5
service:
  extensions:
  - pprof
  - zpages
  - health_check
  pipelines:
    traces:
      receivers:
      - zipkin
      exporters:
      - azuremonitor
      - logging

